apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-init-config
  namespace: monitoring
data:
  setup.sh: |
    #!/bin/bash
    influx setup \
      --username admin \
      --password adminpassword \
      --org mqtt-org \
      --bucket plant_monitoring \
      --retention 7d \
      --force
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: quay.io/influxdb/influxdb:2.7.0
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-data
        - name: init-scripts
          configMap:
            name: influxdb-init-config
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8086
      protocol: TCP
  selector:
    app: influxdb
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-admin-creds
  namespace: monitoring
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5wYXNzd29yZA==
